-- LuxeManage PMS: Room Management Schema
-- Run this in Supabase SQL Editor

-- 1. Rooms table
create table if not exists public.rooms (
  id bigint generated by default as identity primary key,
  number text not null unique,
  floor integer not null,
  type text not null,
  adult_capacity integer not null default 2,
  child_capacity integer not null default 0,
  bed_type text not null,
  base_price numeric(12,2) not null,
  amenities text[] default '{}',
  status text not null default 'vacant_clean',
  description text,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

-- 2. Enable Row Level Security
alter table public.rooms enable row level security;

-- 3. Allow public read/write for development
create policy "public_read_rooms" on public.rooms
  for select using (true);

create policy "public_insert_rooms" on public.rooms
  for insert with check (true);

create policy "public_update_rooms" on public.rooms
  for update using (true);

create policy "public_delete_rooms" on public.rooms
  for delete using (true);

-- 4. Auto-update timestamp
create or replace function public.handle_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger set_updated_at
  before update on public.rooms
  for each row execute procedure public.handle_updated_at();

-- 5. Optional seed data
insert into public.rooms (number, floor, type, adult_capacity, child_capacity, bed_type, base_price, amenities, status)
values
  ('101', 1, 'Standard', 2, 0, 'single', 850000, array['wifi','ac','tv'], 'available'),
  ('102', 1, 'Standard', 2, 1, 'twin', 850000, array['wifi','ac','tv'], 'occupied'),
  ('201', 2, 'Deluxe', 2, 0, 'queen', 1200000, array['wifi','ac','tv','city_view'], 'available'),
  ('202', 2, 'Deluxe', 2, 0, 'king', 1200000, array['wifi','ac','tv','minibar'], 'cleaning'),
  ('301', 3, 'Suite', 2, 0, 'king', 2500000, array['wifi','ac','tv','minibar','bathtub','city_view'], 'occupied'),
  ('302', 3, 'Suite', 2, 1, 'queen', 2500000, array['wifi','ac','tv'], 'maintenance'),
  ('401', 4, 'Executive', 2, 0, 'king', 3500000, array['wifi','ac','tv','minibar','bathtub','city_view'], 'available'),
  ('402', 4, 'Executive', 2, 0, 'king', 3500000, array['wifi','ac','tv','minibar','city_view'], 'occupied')
on conflict (number) do nothing;
